---
- hosts: default
  become: yes
  vars:
    package_list:
      - vsftpd
      - make
    certdir: /etc/pki/tls/certs
    certfile: "{{ ftp_hostname }}.pem"
    certfull: "{{ certdir }}/{{ certfile }}"
    ftp_hostname: localhost
    ftp_listenaddr: 127.0.0.1
    ftp_localroot: /srv
    ftp_username: vagrant
    ftp_password: "{{ lookup('password', '/home/vagrant/.secret') }}"
    ftp_password_hashed: "{{ lookup('password', '/home/vagrant/.secret encrypt=sha512_crypt') }}"
  tasks:
    - package:
        name: "{{ package_list }}"
        state: present
    - command:
        argv:
          - ./make-dummy-cert
          - "{{ certfile }}"
        chdir: "{{ certdir }}"
        creates: "{{ certfull }}"
    - user:
        name: "{{ ftp_username }}"
        password: "{{ ftp_password_hashed }}"
        state: present
    - copy:
        dest: /home/vagrant/.netrc
        owner: vagrant
        group: vagrant
        mode: u=rw,g=,o=
        content: >
          machine {{ ftp_hostname }}
          login {{ ftp_username }}
          password {{ ftp_password }}
    - copy:
        dest: /home/vagrant/testftp.sh
        owner: vagrant
        group: vagrant
        mode: u=rwx,g=rx,o=rx
        content: |
          #!/bin/bash
          set -euo pipefail
          curl -v --netrc --insecure --ssl-reqd ftp://{{ ftp_hostname }}/
    - copy:
        dest: /etc/vsftpd/vsftpd.conf
        owner: root
        group: root
        mode: u=rw,g=,o=
        content: |
          anonymous_enable=NO
          local_enable=YES
          write_enable=YES
          local_umask=022
          dirmessage_enable=YES
          xferlog_enable=YES
          connect_from_port_20=YES
          xferlog_std_format=YES
          listen=YES
          pam_service_name=vsftpd
          userlist_enable=YES
          tcp_wrappers=YES
          banner_file=/etc/issue
          listen_address={{ ftp_listenaddr }}
          local_root={{ ftp_localroot }}
          dual_log_enable=YES
          log_ftp_protocol=YES
          use_localtime=YES
          debug_ssl=YES
          ssl_enable=YES
          rsa_cert_file={{ certfull }}
          force_local_data_ssl=YES
          force_local_logins_ssl=YES
          ssl_sslv2=NO
          ssl_sslv3=NO
          ssl_tlsv1=YES
          ssl_tlsv1_1=YES
          ssl_tlsv1_2=YES
          require_ssl_reuse=NO
          ssl_ciphers=HIGH
          pasv_enable=YES
          pasv_min_port=50000
          pasv_max_port=50050
      notify: restart_vsftpd
    - service:
        name: vsftpd
        state: started
        enabled: yes
  handlers:
    - name: restart_vsftpd
      service:
        name: vsftpd
        state: restarted
